# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: Actions

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with:
          repository: "alliander-opensource/rcdt_public"
          path: "rcdt_public"
          ref: "main"
      - uses: alliander-opensource/ruff-action@v1
        with:
          args: format --check main
      - uses: alliander-opensource/ruff-action@v1
        with:
          args: check --config rcdt_public/pyproject.toml main
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4
  ruffmore:
      runs-on: ubuntu-latest 
      steps:
      - uses: actions/checkout@v4
        with:
          path: main
     - uses: actions/checkout@v4
        with:
          repository: "alliander-opensource/rcdt_public"
          path: "rcdt_public"
          ref: "main"
      - uses: actions/setup-python@v2
      - run: pip install ruff
      - run: | 
        ruff check main
