# SPDX-FileCopyrightText: Alliander N. V.
#
# SPDX-License-Identifier: Apache-2.0

name: Actions

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - uses: actions/checkout@v4
      with:
        repository: "alliander-opensource/rcdt_linting"
        path: "rcdt_linting"
        ref: "main"
    - uses: actions/setup-python@v5
      with:
            python-version: "3.10"
    - run: pip install ruff
    - run: ruff format --check main
    - run: ruff check --config rcdt_linting/config/pyproject.toml main

  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4
